language: ruby

branches:
  only:
    - master

install:
  - nvm install node
  - npm install yaspeller -g
  - gem install jekyll html-proofer jekyll-paginate

script:
  - jekyll build
  - htmlproofer ./_site --disable-external
  - npm test

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache:
    directories:
     - /home/travis/.rvm/

sudo: false # route your build to the container-based infrastructure for a faster build
