language: ruby

rvm:
  - 2.3.3

install:
  - nvm install node
  - npm install yaspeller -g
  - gem install jekyll html-proofer

script:
  - jekyll build
  - htmlproofer ./_site --disable-external
  - npm run spellcheck

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
