name: Surdu
description: really blogging stuff about me ...
meta_description: "Really blogging stuff about Nicu Surdu ..."

markdown: kramdown
logo: false
paginate: 15
baseurl: "/"
domain_name: 'https://surdu.github.io'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://surdu.github.io'
author:         'Nicu Surdu'

disqus-shortname: "surdu-me"

exclude: [
  package.json,
  README.md,
  vendor
]
