name: Surdu
description: really blogging stuff about me ...
meta_description: "Really blogging stuff about Nicu Surdu ..."

markdown: kramdown
logo: false
paginate: 15
baseurl: "/"
domain_name: 'http://surdu.me'
google_analytics: 'UA-19732240-4'
google_search_console: "qS6PD1v2cPj6gw4QeROZgOtRiolrbkSBHAJ7V9RCpFs"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://surdu.me'
author:         'Nicu Surdu'

disqus-shortname: "surdu-me"

exclude: [
  package.json,
  README.md,
  vendor
]
