name: Nicu Surdu
description: Personal blog of Nicu Surdu
meta_description: Personal blog of Nicu Surdu

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: "/"
domain_name: http://surdu.me
google_analytics: UA-19732240-4
google_search_console: "qS6PD1v2cPj6gw4QeROZgOtRiolrbkSBHAJ7V9RCpFs"
plugins: [jekyll-paginate]

twitter: surdume

# Details for the RSS feed generator
url: http://surdu.me
author: Nicu Surdu

disqus-shortname: surdu-me

exclude: [
  package.json,
  README.md,
  vendor
]
